### ISSUE TITLE
Keep notebooks updated to latest QuTiP version release

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip-notebooks#96]
Some notebooks do not run with smoothly with the most recent release.

One could run them every time there is a major release. 
 
The quantum mechanics lectures by @jrjohansson are not updated with latest QuTiP version, and some cells do not run smoothly do to backward compatibility breaks. An [issue](https://groups.google.com/forum/#!topic/qutip/xeVI6M9Z_aY) was recently raised also in the qutip google forum and others were raised in the past. 

In order to have the quantum mechanics lectures updated on the qutip website, at qutip.org/tutorials, I see two options 

- one is to open PRs onto Robert's github repository, 
- another one is to fork the repository inside qutip-notebooks and keep them updated from here. In this second case, it may be nice to add a link at the beginning of notebook pointing to the original repository.

**Comment by IvanIsCoding** [comment]
@nathanshammah 

I am interested in taking this issue. I just have two questions to ask that are connected to this issue.

I think the best solution is to incorporate the quantum lectures to this repository, it is easier to maintain. However, a concern is that I cannot find the license of the notebooks, are we authorized to edit them?  

Another concern is that some notebooks might break again in the future. An idea I have is to use [nbval](https://github.com/computationalmodelling/nbval) to test the Jupyter notebooks. Do you think we should test the notebooks or not? I can open an issue for implementing the nbval tests after this issue is done.

**Comment by hodgestar** [comment]
This is being worked on in https://github.com/qutip/qutip-tutorials, so closing this issue here. We can open more specific issues in the new repository as needed.
